let step = 1; let memberCount = 0; const maxMembers = 4;
const form = document.querySelector('#applicationForm'); const next = document.querySelector('#nextButton'); const prev = document.querySelector('#prevButton'); const notice = document.querySelector('#formNotice');

function showNotice(message,type='error'){notice.textContent=message;notice.className=`notice show ${type}`;notice.scrollIntoView({behavior:'smooth',block:'center'});} function clearNotice(){notice.className='notice';}
function addMember(){if(memberCount>=maxMembers)return;memberCount++;const block=document.createElement('div');block.className='member-block';block.dataset.member=memberCount;block.innerHTML=`<h3>Участник ${memberCount+1}</h3>${memberCount>1?'<button type="button" class="remove-member">Удалить</button>':''}<div class="field-grid"><div class="field"><label class="required">ФИО</label><input data-key="full_name" maxlength="160" required></div><div class="field"><label class="required">Специальность</label><input data-key="specialization" maxlength="180" required></div><div class="field"><label class="required">Учебное заведение</label><input data-key="institution" maxlength="180" required></div><div class="field"><label>Email</label><input data-key="email" type="email" maxlength="254"></div></div>`;block.querySelector('.remove-member')?.addEventListener('click',()=>{block.remove();memberCount--;renumber();});document.querySelector('#members').append(block);}
function renumber(){document.querySelectorAll('.member-block').forEach((block,i)=>block.querySelector('h3').textContent=`Участник ${i+2}`);}
function fieldsForCurrent(){return [...document.querySelector(`.form-step[data-step="${step}"]`).querySelectorAll('input,select,textarea')];}
function validateStep(){clearNotice();for(const field of fieldsForCurrent()){if(!field.checkValidity()){field.reportValidity();return false;}}if(step===2&&document.querySelectorAll('.member-block').length<1){showNotice('Добавьте как минимум одного участника.');return false;}if(step===5){const files=[...document.querySelectorAll('input[type=file]')].flatMap(x=>[...x.files]);if(files.some(file=>file.size>10*1024*1024)){showNotice('Каждый файл должен быть не больше 10 МБ.');return false;}}return true;}
function update(){document.querySelectorAll('.form-step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===step));document.querySelectorAll('.progress-step').forEach((x,i)=>{x.classList.toggle('active',i+1===step);x.classList.toggle('done',i+1<step);});prev.style.visibility=step===1?'hidden':'visible';next.textContent=step===6?'Отправить заявку':'Продолжить →';window.scrollTo({top:document.querySelector('.form-wrap').offsetTop-70,behavior:'smooth'});if(step===6)renderReview();}
function members(){return [...document.querySelectorAll('.member-block')].map(block=>Object.fromEntries([...block.querySelectorAll('[data-key]')].map(input=>[input.dataset.key,input.value.trim()])));}
function renderReview(){const value=id=>document.getElementById(id).value;document.querySelector('#review').innerHTML=`<div class="card" style="margin-bottom:20px"><p><strong>${value('team_name')}</strong> · ${value('region')}</p><p>${MISSION_LABELS[value('mission')]||''}</p><p>${value('project_title')}</p><small>${1+members().length} участников · ${value('leader_email')}</small></div>`;}
async function submit(){if(!validateStep())return;next.disabled=true;next.textContent='Отправляем…';const data=new FormData(form);data.set('members',JSON.stringify(members()));['consent_personal_data','consent_rules','originality_confirmed'].forEach(name=>data.set(name,document.getElementById(name).checked?'true':'false'));try{const result=await api('/applications',{method:'POST',body:data});form.innerHTML=`<div class="success-screen"><div class="success-icon">✓</div><h2>Заявка принята</h2><p>Сохраните номер — он понадобится вместе с email лидера для проверки статуса.</p><div class="tracking-code">${result.data.tracking_code}</div><div style="margin-top:28px"><a class="btn btn-dark" href="/status">Проверить статус →</a></div></div>`;}catch(error){showNotice(error.message);next.disabled=false;next.textContent='Отправить заявку';}}
next.addEventListener('click',()=>{if(!validateStep())return;if(step<6){step++;update();}else submit();});prev.addEventListener('click',()=>{if(step>1){step--;update();}});document.querySelector('#addMember').addEventListener('click',addMember);document.querySelector('#idea_summary').addEventListener('input',e=>document.querySelector('#summaryCount').textContent=e.target.value.length);
api('/public/config').then(result=>{Object.entries(result.data.missions).forEach(([key,label])=>document.querySelector('#mission').add(new Option(label,key)));result.data.regions.forEach(label=>document.querySelector('#region').add(new Option(label,label)));}).catch(()=>showNotice('Не удалось загрузить справочники. Обновите страницу.'));addMember();
